spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

server:
  port : 9081
